### ISSUE TITLE
DEBUG

### ISSUE THREAD

**Issue by laishaoming** [lktlktlkt/ticket-damai#10]
大佬，想问一下为什么会一直加载debug，我搞了build的订单cookie上去也还是这样
![微信图片_20230727152622](https://github.com/lktlktlkt/ticket-damai/assets/88808446/9caf5d8a-96fc-43c5-967e-a1e1f5ec03db)

**Comment by lktlktlkt** [comment]
这算是一个bug，你可以先试试没有折扣的itemId.另外不支持选座
