### ISSUE TITLE
提交订单页面滑动后验证失败

### ISSUE THREAD

**Issue by erhuai** [lktlktlkt/ticket-damai#11]

**Comment by erhuai** [comment]
![image](https://github.com/lktlktlkt/ticket-damai/assets/65691858/1ecc0ccd-116a-4fdc-8b79-fbf561b55052)

**Comment by lktlktlkt** [comment]
刷新页面

**Comment by erhuai** [comment]
> 刷新页面

不行，然后点其他的演出，进入提交订单页面也会出现验证码滑块了。

**Comment by lktlktlkt** [comment]
> > 刷新页面
> 
> 不行，然后点其他的演出，进入提交订单页面也会出现验证码滑块了。

就是需要出现滑块，随便什么演出订单页面都行，滑过去就好了

**Comment by axiliya2568** [comment]
> > 刷新页面
> 
> 不行，然后点其他的演出，进入提交订单页面也会出现验证码滑块了。

请问你是在网页端进入提交订单页面的吗，是怎么进入的啊，为什么我这里提示风险
