### ISSUE TITLE
生成订单：FAIL_SYS_USER_VALIDATE RGV587_ERROR::SM::哎哟喂,被挤爆啦,请稍后重试

### ISSUE THREAD

**Issue by DaoXi-d-X** [lktlktlkt/ticket-damai#17]
damai.performer:submit:77 - 生成订单：FAIL_SYS_USER_VALIDATE RGV587_ERROR::SM::哎哟喂,被挤爆啦,请稍后重试
大佬们这是什么情况

**Comment by lktlktlkt** [comment]
cookie不对

**Comment by KeZhouSeeker** [comment]
performer.py下函数build_order,这个请求data好像要带个bx-ua才行，不然会一直报被挤爆啦。

**Comment by lktlktlkt** [comment]
> performer.py下函数build_order,这个请求data好像要带个bx-ua才行，不然会一直报被挤爆啦。

用15获取cookie的方法，忽略出来的tb页面
