### ISSUE TITLE
error

### ISSUE THREAD

**Issue by little-weakduck** [lktlktlkt/ticket-damai#22]
![image](https://github.com/lktlktlkt/ticket-damai/assets/83490374/3c087201-1790-4fa6-8421-1b9642b12ccb)

**Comment by little-weakduck** [comment]
不知道这啥问题，测试的时候找的随便一个有票的，就报这个错
没票的就会一直刷新

**Comment by lktlktlkt** [comment]
cookie不对，场次可能只有一场

**Comment by little-weakduck** [comment]
哦吼，cookie是从哪里弄吗，直接去把请求头复制下来可以吗。

**Comment by lktlktlkt** [comment]
> 哦吼，cookie是从哪里弄吗，直接去把请求头复制下来可以吗。

按照issues15，然后请求头复制

**Comment by little-weakduck** [comment]
好的好的，谢谢巨老
