### ISSUE TITLE
生成订单成功，创建订单失败

### ISSUE THREAD

**Issue by qihongzhao** [lktlktlkt/ticket-damai#3]
response={'ret': ['FAIL_SYS_USER_VALIDATE', 'RGV587_ERROR::SM::哎哟喂,被挤爆啦,请稍后重试'], 'data': {'url': 'https://mtop.damai.cn:443//h5/mtop.trade.order.create.h5/4.0/_____tmd_____/punish?x5secdata=xd92cb0ada006817e36846c0a78ea70014ab40b16057d16a311689212791a-717315356a1068826063abaac2eaa__bx__mtop.damai.cn%3A443%2Fh5%2Fmtop.trade.order.create.h5%2F4.0&x5step=2&action=captcha&pureCaptcha='}}

**Comment by lktlktlkt** [comment]
要过了验证码后的cookie才能解决这个问题

**Comment by diyongtai** [comment]
> 要过了滑块后的cookie才能解决这个问题

老哥 请教一下怎么样能提前触发一次滑块呢

**Comment by lktlktlkt** [comment]
刷新订单页或者并发请求 这个创建订单正常情况下也有点问题 可以看下获取bx的函数，反馈下
