### ISSUE TITLE
渠道不支持的能抢吗

### ISSUE THREAD

**Issue by qihongzhao** [lktlktlkt/ticket-damai#4]
m.damai.com的详情页显示该渠道不支持购买的是不是会
2023-07-17 12:56:12.435 | INFO     | example.example3:submit:49 - 生成订单：B-00203-200-032::您选购的商品信息已过期，请重新查询

**Comment by lktlktlkt** [comment]
是的

**Comment by qihongzhao** [comment]
那很多热门的票都抢不了，抓包的话，可以模拟接口提交吗

**Comment by Monkey-Bo** [comment]
> 那很多热门的票都抢不了，抓包的话，可以模拟接口提交吗

同问，如果在app内进行抓包，可以模拟接口进行生成订单吗

**Comment by lktlktlkt** [comment]
> 那很多热门的票都抢不了，抓包的话，可以模拟接口提交吗

生成参数，可以提交
