### ISSUE TITLE
能出一期纯小白教程吗

### ISSUE THREAD

**Issue by casterses** [lktlktlkt/ticket-damai#5]

**Comment by lktlktlkt** [comment]
下个push 会修改 尽量多写点readme 。不依赖浏览器。代码应该挺简单吧，没有多少代码。

**Comment by casterses** [comment]
纯小白这一步不明白【终端启动浏览器并登录：
C:\Users\chrome.exe --remote-debugging-port=9222 --user-data-dir="D:\Test"
可执行文件路径                             默认端口                自定义文件夹】，使用终端启动谷歌登录网页版大麦后，点击run.py后弹窗闪退

**Comment by lktlktlkt** [comment]
> 纯小白这一步不明白【终端启动浏览器并登录： C:\Users\chrome.exe --remote-debugging-port=9222 --user-data-dir="D:\Test" 可执行文件路径 默认端口 自定义文件夹】，使用终端启动谷歌登录网页版大麦后，点击run.py后弹窗闪退

安装requirements.txt依赖的模块了吗，是用python解释器执行run.py
